FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS build
RUN apt-get update
RUN apt-get -y install ca-certificates
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN pnpm install --frozen-lockfile
RUN pnpm --filter=app-builder run build
RUN pnpm deploy --filter=app-builder --prod /prod/app-builder

FROM base AS app-builder
ENV NODE_ENV=production
ENV PORT=${PORT:-8080}
RUN apt-get update && apt-get install -y curl
COPY --from=build /prod/app-builder /prod/app-builder
WORKDIR /prod/app-builder
EXPOSE $PORT
CMD [ "pnpm", "start"]
