FROM node:22-slim AS build
RUN apt-get update && apt-get -y install curl ca-certificates
RUN curl -fsSL https://bun.sh/install | bash
ENV PATH="/root/.bun/bin:$PATH"

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN bun install --frozen-lockfile
RUN bun run -F app-builder build
RUN mkdir -p /prod/app-builder && \
    cp -R packages/app-builder/build /prod/app-builder/build && \
    cp -R packages/app-builder/node_modules /prod/app-builder/node_modules

FROM gcr.io/distroless/nodejs22-debian12 AS app-builder
ENV PORT=${PORT:-8080}
COPY --from=build /prod/app-builder/node_modules /prod/app-builder/node_modules
COPY --from=build /prod/app-builder/build /prod/app-builder/build
WORKDIR /prod/app-builder
USER nonroot
EXPOSE $PORT
CMD ["./node_modules/@remix-run/serve/dist/cli.js", "./build/server/index.js"]
