FROM node:22-slim AS build
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN pnpm install --frozen-lockfile
RUN pnpm --filter=app-builder run build
RUN pnpm deploy --filter=app-builder --prod /prod/app-builder

FROM gcr.io/distroless/nodejs22-debian12 AS app-builder
ENV PORT=${PORT:-8080}
COPY --from=build /prod/app-builder/node_modules /prod/app-builder/node_modules
COPY --from=build /prod/app-builder/build /prod/app-builder/build
WORKDIR /prod/app-builder
USER nonroot
EXPOSE $PORT
CMD ["./node_modules/@remix-run/serve/dist/cli.js", "./build/server/index.js"]
