openapi: 3.0.3
info:
  version: 1.0.0
  title: "Feature access API"
  description: "API for retrieving feature access entitlements"
servers:
  - url: "http://localhost:8080"
    description: Local development server
paths:
  /feature_access:
    get:
      summary: Get the entitlements of an organization
      description: Returns the entitlements of an organization
      operationId: getEntitlements
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Feature access response
          content:
            application/json:
              schema:
                type: object
                properties:
                  feature_access:
                    $ref: "#/components/schemas/FeatureAccessDto"
                required:
                  - feature_access
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
components:
  schemas:
    FeatureAccessLevelDto:
      type: string
      enum: ["allowed", "restricted", "test", "missing_configuration"]
    FeatureAccessDto:
      type: object
      properties:
        workflows:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        analytics:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        roles:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        webhooks:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        rule_snoozes:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        test_run:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        sanctions:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        name_recognition:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        ai_assist:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
        auto_assignment:
          $ref: "#/components/schemas/FeatureAccessLevelDto"
      required:
        - workflows
        - analytics
        - roles
        - webhooks
        - rule_snoozes
        - test_run
        - sanctions
        - name_recognition
        - ai_assist
        - auto_assignment
  responses:
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            type: string
            example: Unauthorized
    "403":
      description: Forbidden
      content:
        application/json:
          schema:
            type: string
            example: Forbidden
