openapi: 3.0.3
info:
  version: 1.0.0
  title: 'Feature access API'
  description: 'API for retrieving feature access entitlements'
servers:
  - url: 'http://localhost:8080'
    description: Local development server
paths:
  /is-sso-available:
    get:
      summary: Check if SSO is enabled
      description: Returns true if SSO is enabled
      operationId: isSsoEnabled
      responses:
        '200':
          description: SSO is enabled
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_sso_enabled:
                    type: boolean
                required:
                  - is_sso_enabled
  /feature_access:
    get:
      summary: Get the entitlements of an organization
      description: Returns the entitlements of an organization
      operationId: getEntitlements
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Feature access response
          content:
            application/json:
              schema:
                type: object
                properties:
                  feature_access:
                    $ref: '#/components/schemas/FeatureAccessDto'
                required:
                  - feature_access
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
components:
  schemas:
    FeatureAccessLevelDto:
      type: string
      enum: ['allowed', 'restricted', 'test', 'missing_configuration']
    FeatureAccessDto:
      type: object
      properties:
        workflows:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
        analytics:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
        roles:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
        webhooks:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
        rule_snoozes:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
        test_run:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
        sanctions:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
        ai_assist:
          $ref: '#/components/schemas/FeatureAccessLevelDto'
      required:
        - workflows
        - analytics
        - roles
        - webhooks
        - rule_snoozes
        - test_run
        - sanctions
        - ai_assist
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: string
            example: Unauthorized
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            type: string
            example: Forbidden
