openapi: 3.0.3
info:
  version: 1.0.0
  title: 'License API'
  description: 'API for managing licenses'
servers:
  - url: 'http://localhost:8080'
    description: Local devlopment server
paths:
  /entitlements/{organizationId}:
    get:
      summary: Get the entitlements of an organization
      description: Returns the entitlements of an organization
      operationId: getEntitlements
      parameters:
        - name: organizationId
          description: ID of the organization
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: License validation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LicenseEntitlementsDto'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
components:
  schemas:
    LicenseEntitlementsDto:
      type: object
      properties:
        sso:
          type: boolean
        workflows:
          type: boolean
        analytics:
          type: boolean
        user_roles:
          type: boolean
        webhooks:
          type: boolean
        rule_snoozes:
          type: boolean
        test_run:
          type: boolean
      required:
        - sso
        - workflows
        - analytics
        - user_roles
        - webhooks
        - rule_snoozes
        - test_run
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: string
            example: Unauthorized
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            type: string
            example: Forbidden
