openapi: 3.0.3
info:
  version: 1.0.0
  title: 'Marble Core API'
  description: 'Consume Marble internal endpoints'
tags:
  - name: Admin
    description: Admin operations.
  - name: Data Model
    description: Operations about data model.
  - name: Authorization
    description: Operations about authorization.
  - name: Analytics
    description: Operations about analytics.
  - name: ApiKeys
    description: Operations about api keys.
  - name: Users
    description: Operations about users.
  - name: Organizations
    description: Operations about organizations.
  - name: Decisions
    description: Operations about decisions.
  - name: Cases
    description: Operations about cases.
  - name: Ingestions
    description: Operations about data ingestion.
  - name: Scenarios
    description: Operations about scenarios.
  - name: Scenario Iterations
    description: Operations about scenario iterations.
  - name: Scenario Iteration Rules
    description: Operations about scenario iteration rules.
  - name: Scenario Publications
    description: Operations about scenario publications.
  - name: CustomLists
    description: Operations about custom lists.
  - name: Editor
    description: Operations about editor.
  - name: Tags
    description: Operations about tags.
  - name: Webhooks
    description: Operations about webhooks.
  - name: RuleSnoozes
    description: Operations about rule snoozes.
  - name: TestRun
    description: Operations about testrun.
servers:
  - url: 'http://localhost:8080'
    description: Local devlopment server
paths:
  # AUTHORIZATION

  /token:
    $ref: ./marblecore-api/authorization.yml#/~1token
  /credentials:
    $ref: ./marblecore-api/authorization.yml#/~1credentials

  /decisions/with-ranks: # For ordering, should go down within decisions
    $ref: ./marblecore-api/decisions.yml#/~1decisions~1with-ranks

  # CASES

  /cases:
    $ref: ./marblecore-api/cases.yml#/~1cases
  /cases/{caseId}:
    $ref: ./marblecore-api/cases.yml#/~1cases~1{caseId}
  /cases/{caseId}/assignee:
    $ref: ./marblecore-api/cases.yml#/~1cases~1{caseId}~1assignee
  /cases/{caseId}/decisions:
    $ref: ./marblecore-api/cases.yml#/~1cases~1{caseId}~1decisions
  /cases/{caseId}/comments:
    $ref: ./marblecore-api/cases.yml#/~1cases~1{caseId}~1comments
  /cases/{caseId}/snooze:
    $ref: ./marblecore-api/cases.yml#/~1cases~1{caseId}~1snooze
  /cases/{caseId}/case_tags:
    $ref: ./marblecore-api/cases.yml#/~1cases~1{caseId}~1case_tags
  /cases/files/${caseFileId}/download_link:
    $ref: ./marblecore-api/cases.yml#/~1cases~1files~1${caseFileId}~1download_link
  /cases/review_decision:
    $ref: ./marblecore-api/cases.yml#/~1cases~1review_decision
  /cases/{caseId}/pivot_objects:
    $ref: ./marblecore-api/cases.yml#/~1cases~1{caseId}~1pivot_objects

  # TAGS

  /tags:
    $ref: ./marblecore-api/tags.yml#/~1tags
  /tags/{tagId}:
    $ref: ./marblecore-api/tags.yml#/~1tags~1{tagId}

  # DECISIONS

  /scheduled-executions: # For ordering, should go down
    $ref: ./marblecore-api/decisions.yml#/~1scheduled-executions
  /decisions/{decisionId}:
    $ref: ./marblecore-api/decisions.yml#/~1decisions~1{decisionId}
  /decisions/{decisionId}/active-snoozes:
    $ref: ./marblecore-api/decisions.yml#/~1decisions~1{decisionId}~1active-snoozes
  /decisions/{decisionId}/snooze:
    $ref: ./marblecore-api/decisions.yml#/~1decisions~1{decisionId}~1snooze

  # INGESTION

  /ingestion/{objectType}:
    $ref: ./marblecore-api/ingestion.yml#/~1ingestion~1{objectType}
  /ingestion/{objectType}/upload-logs:
    $ref: ./marblecore-api/ingestion.yml#/~1ingestion~1{objectType}~1upload-logs
  /ingestion/{tableName}/{objectId}:
    $ref: ./marblecore-api/ingestion.yml#/~1ingestion~1{tableName}~1{objectId}
  /client_data/{tableName}/list:
    $ref: ./marblecore-api/ingestion.yml#/~1client_data~1{tableName}~1list

  # CUSTOM LISTS

  /custom-lists:
    $ref: ./marblecore-api/custom-lists.yml#/~1custom-lists
  /custom-lists/{customListId}:
    $ref: ./marblecore-api/custom-lists.yml#/~1custom-lists~1{customListId}
  /custom-lists/{customListId}/values:
    $ref: ./marblecore-api/custom-lists.yml#/~1custom-lists~1{customListId}~1values
  /custom-lists/{customListId}/values/{customListValueId}:
    $ref: ./marblecore-api/custom-lists.yml#/~1custom-lists~1{customListId}~1values~1{customListValueId}

  # SCENARIOS

  /scenarios:
    $ref: ./marblecore-api/scenarios.yml#/~1scenarios
  /scenarios/{scenarioId}:
    $ref: ./marblecore-api/scenarios.yml#/~1scenarios~1{scenarioId}
  /scenarios/{scenarioId}/validate-ast:
    $ref: ./marblecore-api/scenarios.yml#/~1scenarios~1{scenarioId}~1validate-ast

  # SCENARIO ITERATIONS

  /scenario-iterations:
    $ref: ./marblecore-api/scenario-iterations.yml#/~1scenario-iterations
  /scenario-iterations/{scenarioIterationId}:
    $ref: ./marblecore-api/scenario-iterations.yml#/~1scenario-iterations~1{scenarioIterationId}
  /scenario-iterations/{scenarioIterationId}/schedule-execution:
    $ref: ./marblecore-api/scenario-iterations.yml#/~1scenario-iterations~1{scenarioIterationId}~1schedule-execution
  /scenario-iterations/{scenarioIterationId}/validate:
    $ref: ./marblecore-api/scenario-iterations.yml#/~1scenario-iterations~1{scenarioIterationId}~1validate
  /scenario-iterations/{scenarioIterationId}/active-snoozes:
    $ref: ./marblecore-api/scenario-iterations.yml#/~1scenario-iterations~1{scenarioIterationId}~1active-snoozes
  /scenario-iterations/{scenarioIterationId}/commit:
    $ref: ./marblecore-api/scenario-iterations.yml#/~1scenario-iterations~1{scenarioIterationId}~1commit
  /scenario-iterations/{scenarioIterationId}/sanction-check:
    $ref: ./marblecore-api/scenario-iterations.yml#/~1scenario-iterations~1{scenarioIterationId}~1sanction-check

  # SANCTION CHECKS

  /sanction-checks:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks
  /sanction-checks/datasets:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks~1datasets
  /sanction-checks/{sanctionCheckId}/files:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks~1{sanctionCheckId}~1files
  /sanction-checks/matches/{matchId}:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks~1matches~1{matchId}
  /sanction-checks/matches/{matchId}/enrich:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks~1matches~1{matchId}~1enrich
  /sanction-checks/search:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks~1search
  /sanction-checks/refine:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks~1refine
  /sanction-checks/freshness:
    $ref: ./marblecore-api/sanction-checks.yml#/~1sanction-checks~1freshness

  # RULES

  /scenario-iteration-rules:
    $ref: ./marblecore-api/scenario-iteration-rules.yml#/~1scenario-iteration-rules
  /scenario-iteration-rules/{ruleId}:
    $ref: ./marblecore-api/scenario-iteration-rules.yml#/~1scenario-iteration-rules~1{ruleId}

  # SCENARIO PUBLICATIONS

  /scenario-publications:
    $ref: ./marblecore-api/scenario-publications.yml#/~1scenario-publications
  /scenario-publications/preparation:
    $ref: ./marblecore-api/scenario-publications.yml#/~1scenario-publications~1preparation
  /scenario-publications/{scenarioPublicationId}:
    $ref: ./marblecore-api/scenario-publications.yml#/~1scenario-publications~1{scenarioPublicationId}

  # DATA MODEL

  /data-model:
    $ref: ./marblecore-api/data-model.yml#/~1data-model
  /data-model/tables:
    $ref: ./marblecore-api/data-model.yml#/~1data-model~1tables
  /data-model/tables/{tableId}:
    $ref: ./marblecore-api/data-model.yml#/~1data-model~1tables~1{tableId}
  /data-model/tables/{tableId}/fields:
    $ref: ./marblecore-api/data-model.yml#/~1data-model~1tables~1{tableId}~1fields
  /data-model/fields/{fieldId}:
    $ref: ./marblecore-api/data-model.yml#/~1data-model~1fields~1{fieldId}
  /data-model/links:
    $ref: ./marblecore-api/data-model.yml#/~1data-model~1links
  /data-model/openapi:
    $ref: ./marblecore-api/data-model.yml#/~1data-model~1openapi
  /data-model/pivots:
    $ref: ./marblecore-api/data-model.yml#/~1data-model~1pivots

  # MISC

  /analytics:
    $ref: ./marblecore-api/misc.yml#/~1analytics

  # ADMINISTRATION

  /apikeys:
    $ref: ./marblecore-api/admin.yml#/~1apikeys
  /apikeys/{apiKeyId}:
    $ref: ./marblecore-api/admin.yml#/~1apikeys~1{apiKeyId}
  /users:
    $ref: ./marblecore-api/admin.yml#/~1users
  /users/{userId}:
    $ref: ./marblecore-api/admin.yml#/~1users~1{userId}
  /organizations:
    $ref: ./marblecore-api/admin.yml#/~1organizations
  /organizations/{organizationId}:
    $ref: ./marblecore-api/admin.yml#/~1organizations~1{organizationId}
  /organizations/{organizationId}/users:
    $ref: ./marblecore-api/admin.yml#/~1organizations~1{organizationId}~1users
  /editor/{scenarioId}/identifiers:
    $ref: ./marblecore-api/misc.yml#/~1editor~1{scenarioId}~1identifiers

  # INBOXES

  /inboxes:
    $ref: ./marblecore-api/inboxes.yml#/~1inboxes
  /inboxes/{inboxId}:
    $ref: ./marblecore-api/inboxes.yml#/~1inboxes~1{inboxId}
  /inboxes/{inboxId}/users:
    $ref: ./marblecore-api/inboxes.yml#/~1inboxes~1{inboxId}~1users
  /inbox_users:
    $ref: ./marblecore-api/inboxes.yml#/~1inbox_users
  /inbox_users/{inboxUserId}:
    $ref: ./marblecore-api/inboxes.yml#/~1inbox_users~1{inboxUserId}

  # WEBHOOKS

  /webhooks:
    $ref: ./marblecore-api/webhooks.yml#/~1webhooks
  /webhooks/{webhookId}:
    $ref: ./marblecore-api/webhooks.yml#/~1webhooks~1{webhookId}

  # RULE SNOOZES

  /rule-snoozes/{rule_snooze_id}:
    $ref: ./marblecore-api/rule-snoozes.yml#/~1rule-snoozes~1{rule_snooze_id}

  # TEST RUNS

  /scenario-testrun:
    $ref: ./marblecore-api/scenario-testrun.yml#/~1scenario-testrun
  /scenario-testruns/{test_run_id}:
    $ref: ./marblecore-api/scenario-testrun.yml#/~1scenario-testruns~1{test_run_id}
  /scenario-testruns/{test_run_id}/cancel:
    $ref: ./marblecore-api/scenario-testrun.yml#/~1scenario-testruns~1{test_run_id}~1cancel
  /scenario-testruns/{test_run_id}/decision_data_by_score:
    $ref: ./marblecore-api/scenario-testrun.yml#/~1scenario-testruns~1{test_run_id}~1decision_data_by_score
  /scenario-testruns/{test_run_id}/data_by_rule_execution:
    $ref: ./marblecore-api/scenario-testrun.yml#/~1scenario-testruns~1{test_run_id}~1data_by_rule_execution

  # VERSION
  /version:
    $ref: ./marblecore-api/version.yml#/~1version

  # SIGNUP STATUS
  /signup-status:
    $ref: ./marblecore-api/signup-status.yml#/~1signup-status
components:
  securitySchemes:
    $ref: marblecore-api/_common.yml#/securitySchemes
  parameters:
    $ref: marblecore-api/_common.yml#/parameters
  responses:
    $ref: marblecore-api/_common.yml#/responses
  schemas:
    $ref: marblecore-api/_schemas.yml
