openapi: 3.0.3
info:
  version: 1.0.0
  title: 'License API'
  description: 'API for managing scenario in test mode'
servers:
  - url: 'http://localhost:8080'
    description: Local devlopment server
paths:
  /scenario-testrun:
    post:
      summary: Create a test run
      operationId: postTestRun
      security:
        - bearerAuth: []
      requestBody:
       content:
         application/json:
           schema:
             type: object
             properties:
               scenario_iteration_id:
                 type: string
                 format: uuid
               scenario_id:
                 type: string
                 format: uuid
               period:
                 type: string
             required:
               - scenario_iteration_id
               - scenario_id
               - period
       required: true
      responses:
        '201':
          description: the newly created testrun
          content:
            application/json:
              schema:
                type: object
                properties:
                  scenario_id:
                    type: string
                  period:
                    type: string
                  status:
                    type:string
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
  /scenario-testruns/{scenario_id}:
    get:
      summary: Get testruns by scenario id
      operationId: testrunsByScenatioId
      security:
       - bearerAuth: []
      parameters:
       - name: scenario_id
         description: the Id of the  scenario
         in: path
         required: true
         schema:
           type: string
           format: uuid
      responses:
        '200':
          description: List of corresponding testruns
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Testrun'
                      
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
components:
  schemas:
   Testrun:
     type: object
     required:
       - scenario_iteration_id
       - begin
       - end
     properties:
       scenario_iteration_id:
         type: string
         format: uuid
       begin:
         type: string
         format: date
       end:
         type: string
         format: date
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: string
            example: Unauthorized
    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            type: string
            example: Forbidden
