/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPublicRouteImport } from './routes/_app/_public'
import { Route as AppPrivateRouteImport } from './routes/_app/_private'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as AppPublicSignInRouteImport } from './routes/_app/_public/sign-in'
import { Route as AppPrivateDashboardRouteImport } from './routes/_app/_private/dashboard'
import { Route as AppPrivateOrganizationsIndexRouteImport } from './routes/_app/_private/organizations/index'
import { Route as AppPrivateOrganizationsOrgIdRouteImport } from './routes/_app/_private/organizations/$orgId'
import { Route as AppPrivateOrganizationsOrgIdIndexRouteImport } from './routes/_app/_private/organizations/$orgId.index'
import { Route as AppPrivateOrganizationsOrgIdUsersRouteImport } from './routes/_app/_private/organizations/$orgId.users'
import { Route as AppPrivateOrganizationsOrgIdSettingsRouteImport } from './routes/_app/_private/organizations/$orgId.settings'
import { Route as AppPrivateOrganizationsOrgIdFeaturesRouteImport } from './routes/_app/_private/organizations/$orgId.features'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPublicRoute = AppPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivateRoute = AppPrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => AppRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPublicSignInRoute = AppPublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AppPublicRoute,
} as any)
const AppPrivateDashboardRoute = AppPrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppPrivateRoute,
} as any)
const AppPrivateOrganizationsIndexRoute =
  AppPrivateOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AppPrivateRoute,
  } as any)
const AppPrivateOrganizationsOrgIdRoute =
  AppPrivateOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AppPrivateRoute,
  } as any)
const AppPrivateOrganizationsOrgIdIndexRoute =
  AppPrivateOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppPrivateOrganizationsOrgIdRoute,
  } as any)
const AppPrivateOrganizationsOrgIdUsersRoute =
  AppPrivateOrganizationsOrgIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AppPrivateOrganizationsOrgIdRoute,
  } as any)
const AppPrivateOrganizationsOrgIdSettingsRoute =
  AppPrivateOrganizationsOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppPrivateOrganizationsOrgIdRoute,
  } as any)
const AppPrivateOrganizationsOrgIdFeaturesRoute =
  AppPrivateOrganizationsOrgIdFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => AppPrivateOrganizationsOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppPrivateDashboardRoute
  '/sign-in': typeof AppPublicSignInRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/organizations/$orgId': typeof AppPrivateOrganizationsOrgIdRouteWithChildren
  '/organizations/': typeof AppPrivateOrganizationsIndexRoute
  '/organizations/$orgId/features': typeof AppPrivateOrganizationsOrgIdFeaturesRoute
  '/organizations/$orgId/settings': typeof AppPrivateOrganizationsOrgIdSettingsRoute
  '/organizations/$orgId/users': typeof AppPrivateOrganizationsOrgIdUsersRoute
  '/organizations/$orgId/': typeof AppPrivateOrganizationsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppPrivateDashboardRoute
  '/sign-in': typeof AppPublicSignInRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/organizations': typeof AppPrivateOrganizationsIndexRoute
  '/organizations/$orgId/features': typeof AppPrivateOrganizationsOrgIdFeaturesRoute
  '/organizations/$orgId/settings': typeof AppPrivateOrganizationsOrgIdSettingsRoute
  '/organizations/$orgId/users': typeof AppPrivateOrganizationsOrgIdUsersRoute
  '/organizations/$orgId': typeof AppPrivateOrganizationsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_private': typeof AppPrivateRouteWithChildren
  '/_app/_public': typeof AppPublicRouteWithChildren
  '/_app/_private/dashboard': typeof AppPrivateDashboardRoute
  '/_app/_public/sign-in': typeof AppPublicSignInRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_app/_private/organizations/$orgId': typeof AppPrivateOrganizationsOrgIdRouteWithChildren
  '/_app/_private/organizations/': typeof AppPrivateOrganizationsIndexRoute
  '/_app/_private/organizations/$orgId/features': typeof AppPrivateOrganizationsOrgIdFeaturesRoute
  '/_app/_private/organizations/$orgId/settings': typeof AppPrivateOrganizationsOrgIdSettingsRoute
  '/_app/_private/organizations/$orgId/users': typeof AppPrivateOrganizationsOrgIdUsersRoute
  '/_app/_private/organizations/$orgId/': typeof AppPrivateOrganizationsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/trpc/$'
    | '/organizations/$orgId'
    | '/organizations/'
    | '/organizations/$orgId/features'
    | '/organizations/$orgId/settings'
    | '/organizations/$orgId/users'
    | '/organizations/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/trpc/$'
    | '/organizations'
    | '/organizations/$orgId/features'
    | '/organizations/$orgId/settings'
    | '/organizations/$orgId/users'
    | '/organizations/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_private'
    | '/_app/_public'
    | '/_app/_private/dashboard'
    | '/_app/_public/sign-in'
    | '/api/trpc/$'
    | '/_app/_private/organizations/$orgId'
    | '/_app/_private/organizations/'
    | '/_app/_private/organizations/$orgId/features'
    | '/_app/_private/organizations/$orgId/settings'
    | '/_app/_private/organizations/$orgId/users'
    | '/_app/_private/organizations/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_public': {
      id: '/_app/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPublicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_private': {
      id: '/_app/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppPrivateRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_public/sign-in': {
      id: '/_app/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AppPublicSignInRouteImport
      parentRoute: typeof AppPublicRoute
    }
    '/_app/_private/dashboard': {
      id: '/_app/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppPrivateDashboardRouteImport
      parentRoute: typeof AppPrivateRoute
    }
    '/_app/_private/organizations/': {
      id: '/_app/_private/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AppPrivateOrganizationsIndexRouteImport
      parentRoute: typeof AppPrivateRoute
    }
    '/_app/_private/organizations/$orgId': {
      id: '/_app/_private/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AppPrivateOrganizationsOrgIdRouteImport
      parentRoute: typeof AppPrivateRoute
    }
    '/_app/_private/organizations/$orgId/': {
      id: '/_app/_private/organizations/$orgId/'
      path: '/'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof AppPrivateOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof AppPrivateOrganizationsOrgIdRoute
    }
    '/_app/_private/organizations/$orgId/users': {
      id: '/_app/_private/organizations/$orgId/users'
      path: '/users'
      fullPath: '/organizations/$orgId/users'
      preLoaderRoute: typeof AppPrivateOrganizationsOrgIdUsersRouteImport
      parentRoute: typeof AppPrivateOrganizationsOrgIdRoute
    }
    '/_app/_private/organizations/$orgId/settings': {
      id: '/_app/_private/organizations/$orgId/settings'
      path: '/settings'
      fullPath: '/organizations/$orgId/settings'
      preLoaderRoute: typeof AppPrivateOrganizationsOrgIdSettingsRouteImport
      parentRoute: typeof AppPrivateOrganizationsOrgIdRoute
    }
    '/_app/_private/organizations/$orgId/features': {
      id: '/_app/_private/organizations/$orgId/features'
      path: '/features'
      fullPath: '/organizations/$orgId/features'
      preLoaderRoute: typeof AppPrivateOrganizationsOrgIdFeaturesRouteImport
      parentRoute: typeof AppPrivateOrganizationsOrgIdRoute
    }
  }
}

interface AppPrivateOrganizationsOrgIdRouteChildren {
  AppPrivateOrganizationsOrgIdFeaturesRoute: typeof AppPrivateOrganizationsOrgIdFeaturesRoute
  AppPrivateOrganizationsOrgIdSettingsRoute: typeof AppPrivateOrganizationsOrgIdSettingsRoute
  AppPrivateOrganizationsOrgIdUsersRoute: typeof AppPrivateOrganizationsOrgIdUsersRoute
  AppPrivateOrganizationsOrgIdIndexRoute: typeof AppPrivateOrganizationsOrgIdIndexRoute
}

const AppPrivateOrganizationsOrgIdRouteChildren: AppPrivateOrganizationsOrgIdRouteChildren =
  {
    AppPrivateOrganizationsOrgIdFeaturesRoute:
      AppPrivateOrganizationsOrgIdFeaturesRoute,
    AppPrivateOrganizationsOrgIdSettingsRoute:
      AppPrivateOrganizationsOrgIdSettingsRoute,
    AppPrivateOrganizationsOrgIdUsersRoute:
      AppPrivateOrganizationsOrgIdUsersRoute,
    AppPrivateOrganizationsOrgIdIndexRoute:
      AppPrivateOrganizationsOrgIdIndexRoute,
  }

const AppPrivateOrganizationsOrgIdRouteWithChildren =
  AppPrivateOrganizationsOrgIdRoute._addFileChildren(
    AppPrivateOrganizationsOrgIdRouteChildren,
  )

interface AppPrivateRouteChildren {
  AppPrivateDashboardRoute: typeof AppPrivateDashboardRoute
  AppPrivateOrganizationsOrgIdRoute: typeof AppPrivateOrganizationsOrgIdRouteWithChildren
  AppPrivateOrganizationsIndexRoute: typeof AppPrivateOrganizationsIndexRoute
}

const AppPrivateRouteChildren: AppPrivateRouteChildren = {
  AppPrivateDashboardRoute: AppPrivateDashboardRoute,
  AppPrivateOrganizationsOrgIdRoute:
    AppPrivateOrganizationsOrgIdRouteWithChildren,
  AppPrivateOrganizationsIndexRoute: AppPrivateOrganizationsIndexRoute,
}

const AppPrivateRouteWithChildren = AppPrivateRoute._addFileChildren(
  AppPrivateRouteChildren,
)

interface AppPublicRouteChildren {
  AppPublicSignInRoute: typeof AppPublicSignInRoute
}

const AppPublicRouteChildren: AppPublicRouteChildren = {
  AppPublicSignInRoute: AppPublicSignInRoute,
}

const AppPublicRouteWithChildren = AppPublicRoute._addFileChildren(
  AppPublicRouteChildren,
)

interface AppRouteChildren {
  AppPrivateRoute: typeof AppPrivateRouteWithChildren
  AppPublicRoute: typeof AppPublicRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppPrivateRoute: AppPrivateRouteWithChildren,
  AppPublicRoute: AppPublicRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
