/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as PrivateDashboardRouteImport } from './routes/_private/dashboard'
import { Route as PrivateOrganizationsIndexRouteImport } from './routes/_private/organizations/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as PrivateOrganizationsOrgIdRouteImport } from './routes/_private/organizations/$orgId'
import { Route as PrivateOrganizationsOrgIdIndexRouteImport } from './routes/_private/organizations/$orgId.index'
import { Route as PrivateOrganizationsOrgIdUsersRouteImport } from './routes/_private/organizations/$orgId.users'
import { Route as PrivateOrganizationsOrgIdSettingsRouteImport } from './routes/_private/organizations/$orgId.settings'
import { Route as PrivateOrganizationsOrgIdFeaturesRouteImport } from './routes/_private/organizations/$orgId.features'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PrivateDashboardRoute = PrivateDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateOrganizationsIndexRoute =
  PrivateOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => PrivateRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateOrganizationsOrgIdRoute =
  PrivateOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => PrivateRoute,
  } as any)
const PrivateOrganizationsOrgIdIndexRoute =
  PrivateOrganizationsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateOrganizationsOrgIdRoute,
  } as any)
const PrivateOrganizationsOrgIdUsersRoute =
  PrivateOrganizationsOrgIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => PrivateOrganizationsOrgIdRoute,
  } as any)
const PrivateOrganizationsOrgIdSettingsRoute =
  PrivateOrganizationsOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PrivateOrganizationsOrgIdRoute,
  } as any)
const PrivateOrganizationsOrgIdFeaturesRoute =
  PrivateOrganizationsOrgIdFeaturesRouteImport.update({
    id: '/features',
    path: '/features',
    getParentRoute: () => PrivateOrganizationsOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/sign-in': typeof PublicSignInRoute
  '/organizations/$orgId': typeof PrivateOrganizationsOrgIdRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/organizations/': typeof PrivateOrganizationsIndexRoute
  '/organizations/$orgId/features': typeof PrivateOrganizationsOrgIdFeaturesRoute
  '/organizations/$orgId/settings': typeof PrivateOrganizationsOrgIdSettingsRoute
  '/organizations/$orgId/users': typeof PrivateOrganizationsOrgIdUsersRoute
  '/organizations/$orgId/': typeof PrivateOrganizationsOrgIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof PrivateDashboardRoute
  '/sign-in': typeof PublicSignInRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/organizations': typeof PrivateOrganizationsIndexRoute
  '/organizations/$orgId/features': typeof PrivateOrganizationsOrgIdFeaturesRoute
  '/organizations/$orgId/settings': typeof PrivateOrganizationsOrgIdSettingsRoute
  '/organizations/$orgId/users': typeof PrivateOrganizationsOrgIdUsersRoute
  '/organizations/$orgId': typeof PrivateOrganizationsOrgIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_private/dashboard': typeof PrivateDashboardRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_private/organizations/$orgId': typeof PrivateOrganizationsOrgIdRouteWithChildren
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_private/organizations/': typeof PrivateOrganizationsIndexRoute
  '/_private/organizations/$orgId/features': typeof PrivateOrganizationsOrgIdFeaturesRoute
  '/_private/organizations/$orgId/settings': typeof PrivateOrganizationsOrgIdSettingsRoute
  '/_private/organizations/$orgId/users': typeof PrivateOrganizationsOrgIdUsersRoute
  '/_private/organizations/$orgId/': typeof PrivateOrganizationsOrgIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/organizations/$orgId'
    | '/api/trpc/$'
    | '/organizations/'
    | '/organizations/$orgId/features'
    | '/organizations/$orgId/settings'
    | '/organizations/$orgId/users'
    | '/organizations/$orgId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/api/trpc/$'
    | '/organizations'
    | '/organizations/$orgId/features'
    | '/organizations/$orgId/settings'
    | '/organizations/$orgId/users'
    | '/organizations/$orgId'
  id:
    | '__root__'
    | '/'
    | '/_private'
    | '/_public'
    | '/_private/dashboard'
    | '/_public/sign-in'
    | '/_private/organizations/$orgId'
    | '/api/trpc/$'
    | '/_private/organizations/'
    | '/_private/organizations/$orgId/features'
    | '/_private/organizations/$orgId/settings'
    | '/_private/organizations/$orgId/users'
    | '/_private/organizations/$orgId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_private/dashboard': {
      id: '/_private/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/organizations/': {
      id: '/_private/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof PrivateOrganizationsIndexRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/organizations/$orgId': {
      id: '/_private/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof PrivateOrganizationsOrgIdRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/organizations/$orgId/': {
      id: '/_private/organizations/$orgId/'
      path: '/'
      fullPath: '/organizations/$orgId/'
      preLoaderRoute: typeof PrivateOrganizationsOrgIdIndexRouteImport
      parentRoute: typeof PrivateOrganizationsOrgIdRoute
    }
    '/_private/organizations/$orgId/users': {
      id: '/_private/organizations/$orgId/users'
      path: '/users'
      fullPath: '/organizations/$orgId/users'
      preLoaderRoute: typeof PrivateOrganizationsOrgIdUsersRouteImport
      parentRoute: typeof PrivateOrganizationsOrgIdRoute
    }
    '/_private/organizations/$orgId/settings': {
      id: '/_private/organizations/$orgId/settings'
      path: '/settings'
      fullPath: '/organizations/$orgId/settings'
      preLoaderRoute: typeof PrivateOrganizationsOrgIdSettingsRouteImport
      parentRoute: typeof PrivateOrganizationsOrgIdRoute
    }
    '/_private/organizations/$orgId/features': {
      id: '/_private/organizations/$orgId/features'
      path: '/features'
      fullPath: '/organizations/$orgId/features'
      preLoaderRoute: typeof PrivateOrganizationsOrgIdFeaturesRouteImport
      parentRoute: typeof PrivateOrganizationsOrgIdRoute
    }
  }
}

interface PrivateOrganizationsOrgIdRouteChildren {
  PrivateOrganizationsOrgIdFeaturesRoute: typeof PrivateOrganizationsOrgIdFeaturesRoute
  PrivateOrganizationsOrgIdSettingsRoute: typeof PrivateOrganizationsOrgIdSettingsRoute
  PrivateOrganizationsOrgIdUsersRoute: typeof PrivateOrganizationsOrgIdUsersRoute
  PrivateOrganizationsOrgIdIndexRoute: typeof PrivateOrganizationsOrgIdIndexRoute
}

const PrivateOrganizationsOrgIdRouteChildren: PrivateOrganizationsOrgIdRouteChildren =
  {
    PrivateOrganizationsOrgIdFeaturesRoute:
      PrivateOrganizationsOrgIdFeaturesRoute,
    PrivateOrganizationsOrgIdSettingsRoute:
      PrivateOrganizationsOrgIdSettingsRoute,
    PrivateOrganizationsOrgIdUsersRoute: PrivateOrganizationsOrgIdUsersRoute,
    PrivateOrganizationsOrgIdIndexRoute: PrivateOrganizationsOrgIdIndexRoute,
  }

const PrivateOrganizationsOrgIdRouteWithChildren =
  PrivateOrganizationsOrgIdRoute._addFileChildren(
    PrivateOrganizationsOrgIdRouteChildren,
  )

interface PrivateRouteChildren {
  PrivateDashboardRoute: typeof PrivateDashboardRoute
  PrivateOrganizationsOrgIdRoute: typeof PrivateOrganizationsOrgIdRouteWithChildren
  PrivateOrganizationsIndexRoute: typeof PrivateOrganizationsIndexRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateDashboardRoute: PrivateDashboardRoute,
  PrivateOrganizationsOrgIdRoute: PrivateOrganizationsOrgIdRouteWithChildren,
  PrivateOrganizationsIndexRoute: PrivateOrganizationsIndexRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
