name: Reusable build and deploy job

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Github environment to use'
        required: true
    secrets:
      GCP_SA_KEY:
        required: true
        description: 'GCP Service Account Key'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    environment: ${{ inputs.environment }}
    env:
      TAG: europe-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/marble/marble-frontend:latest
      SERVICE_ACCOUNT: marble-frontend-cloud-run@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: beta

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          target: app-builder
          tags: ${{ env.TAG }}

      - name: Deploy server
        run: |
          gcloud run deploy marble-frontend \
            --quiet \
            --image="${{ env.TAG }}"
