name: Reusable build and deploy job

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Github environment to use'
        required: true
      version:
        type: string
        description: 'version to deploy'
        required: true
    secrets:
      GCP_SA_KEY:
        required: true
        description: 'GCP Service Account Key'
      SENTRY_AUTH_TOKEN:
        required: true
        description: 'Sentry Auth Token'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    environment: ${{ inputs.environment }}
    env:
      IMAGE: europe-west1-docker.pkg.dev/marble-infra/marble/marble-frontend:${{ inputs.version }}
      SERVICE_ACCOUNT: marble-frontend-cloud-run@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # source: https://github.com/docker/login-action#google-artifact-registry-gar
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1
        with:
          token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          organization: 'checkmarble'
          project: 'marble-frontend'

      - name: Get release
        run: |
          echo "SENTRY_RELEASE=$(sentry-cli releases propose-version)" >> "$GITHUB_ENV"

      # source: https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: app-builder
          tags: ${{ env.IMAGE }}
          file: ./Dockerfile
          build-args: |
            "SENTRY_RELEASE=${{ env.SENTRY_RELEASE }}"
          secrets: |
            "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}"

      - name: Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: beta

      - name: Deploy server
        run: |
          gcloud run deploy marble-frontend \
            --quiet \
            --region="europe-west1" \
            --image="${{ env.IMAGE }}"
