name: E2E tests
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.21
      - name: Cache Bun
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - run: bun run -F tests test:install
      - run: bun run -F tests test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: |
            packages/tests/playwright-report/
            packages/tests/trace.zip
          retention-days: 1
