name: Pull request CI

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/check.yaml
