name: Push a tag (Check & Deploy)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/check.yaml

  build_and_deploy:
    needs: check
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/build_and_deploy.yaml
    with:
      environment: 'production'
      version: ${{ github.ref_name }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_PRODUCTION }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
