name: Push a tag (Check & Deploy)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    permissions:
      contents: read
      actions: read
    uses: ./.github/workflows/check.yaml

  build_and_deploy:
    needs: check
    permissions:
      contents: read
      actions: read
      id-token: 'write' # needed for using open id token to authenticate with GCP
    uses: ./.github/workflows/build_and_deploy.yaml
    with:
      environment: 'production'
      version: ${{ github.ref_name }}
      SENTRY_RELEASE: ${{ github.ref_name }}
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SEGMENT_WRITE_KEY_OPENSOURCE: ${{ secrets.SEGMENT_WRITE_KEY_OPENSOURCE }}
